### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by ethiy** [IGNF/gilviewer#15]
After creating a unix build file, I get an error message trying to  build the target all:

``` bash
make all -j8
```

I get the following error message:

``` txt
[ 58%] Building CXX object CMakeFiles/GilViewer.dir/src/GilViewer/gui/resources/resources.cpp.o
In file included from /usr/local/include/png.h:363:0,
                 from /home/ethiy/Workspace/3rdParty/gilviewer/extern/boost/gil/extension/io_new/png_tags.hpp:23,
                 from /home/ethiy/Workspace/3rdParty/gilviewer/extern/boost/gil/extension/io_new/png_read.hpp:22,
                 from /home/ethiy/Workspace/3rdParty/gilviewer/extern/boost/gil/extension/io_new/png_all.hpp:22,
                 from /home/ethiy/Workspace/3rdParty/gilviewer/src/GilViewer/io/gilviewer_file_io_png.hpp:41,
                 from /home/ethiy/Workspace/3rdParty/gilviewer/src/GilViewer/io/gilviewer_io_factory.cpp:8:
/usr/local/include/pngconf.h: At global scope:
/usr/local/include/pngconf.h:307:10: error: ‘__png’ does not name a type
          __png.h__ already includes setjmp.h;
          ^
/usr/local/include/pngconf.h:308:10: error: ‘__dont__’ does not name a type
          __dont__ include it again.;
          ^

```

I am working on a ubuntu xenial (16.04)
